name: Java deployemt workflow
on: push
jobs:
  build_and_test:
     runs-on: ubuntu-latest
     steps: 
       - name: Get Code
         uses: actions/checkout@v4
       - name: Set up JDK 21
         uses: actions/setup-java@v4  
         with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'   
       - name: Build project with Maven
         run: mvn -B package --file pom.xml
    