name: Java Springboot Project with Reuseable
on: 
 push:
    branches:
        - main
jobs:     
   test: 
     runs-on: ubuntu-latest
     steps:
      -  id: checkout-out
         name: Checkout
         uses: actions/checkout@v4
      -  name: Set java env
         uses: actions/setup-java@v4
         with: 
            distribution: 'oracle'   
            java-version: '21'
      - name: Cache the Maven packages
        id: cache  
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      -  name: Install dependencys
         if: steps.cache.outputs.cache-hit != 'true'
         run: mvn dependency:resolve         
      -  name: Unit Testing
         id: testing-code
         run: mvn  test
      -  name: Upload test Report
         if: failure() && steps.testing-code.outcome == 'failure'
         uses: actions/upload-artifact@v4
         with:
            path: target/surefire-reports/*.xml
            name: test-report   
   build:
        needs: test
        runs-on: ubuntu-latest
        outputs:
          artifact-file: ${{ steps.publish.outputs.artifact}}
        steps: 
         -  id: checkout-out
            name: Checkout
            uses: actions/checkout@v4
         -  name: Set java env
            uses: actions/setup-java@v4
            with: 
               distribution: 'oracle'   
               java-version: '21'    
         -  name: Cache the Maven packages
            id: cache  
            uses: actions/cache@v4
            with: 
               path: ~/.m2
               key:  ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}      
               restore-keys: ${{ runner.os }}-m2  
         -  name: Install dependencys
            if: steps.cache.outputs.cache-hit != 'true'
            run: mvn dependency:resolve          
         -  name:  Build with Maven
            run:   mvn clean install  -Dmaven.test.skip=true
         -  name: Publish
            id: publish
            run: find target/*.jar -type f -execdir echo 'artifact={}' >> $GITHUB_OUTPUT ';'     
         -  name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
               path: target/*.jar
               name: package          
   deploye:
      needs: build
      runs-on: ubuntu-latest
      steps: 
       -  id: checkout-out
          name: Checkout
          uses: actions/checkout@v4        
       -  name: Get build artifact
          uses: actions/download-artifact@v4
          with:
            name: package
       - name: Set java env
         uses: actions/setup-java@v4
         with:
           distribution: 'oracle'
           java-version: '21'
       -  name:  Run Spring Boot
          run:  echo "$MYSQL_ROOT_PASSWORD"
       -  name: get artifact name
          run : echo ${{ needs.build.outputs.artifact-file }}  
       -  name: Deploy
          run: echo "Deploying...."      
   report:
      if: failure()
      needs: [test,deploye,build]
      runs-on: ubuntu-latest
      steps:
       - name: Output Information
         run: |
            echo "Something went wrong"
            echo "${{ toJson(github) }}"
   reuable-workflow:
      needs: build   
      uses: ./.gihub/workflows/reuseable.yml       


      
