name: New Deployment Java Project
on: 
 push:
    branches:
        - main
jobs:
   test:
     runs-on: ubuntu-latest
     services:
       mysql:
         image: mysql
         env:
           MYSQL_ROOT_PASSWORD: adminadmin
     steps:
      -  id: checkout-out
         name: Checkout
         uses: actions/checkout@v4
      -  name: Set java env
         uses: actions/setup-java@v4
         with: 
            distribution: 'oracle'   
            java-version: '21'
      - name: Cache the Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      -  name: Unit Testing
         run: mvn "-Dtest=EmployeeControllerTest" test
   build:
        needs: test
        runs-on: ubuntu-latest
        outputs:
          artifact-file: ${{ steps.publish.outputs.artifact}}
        steps: 
         -  id: checkout-out
            name: Checkout
            uses: actions/checkout@v4
         -  name: Set java env
            uses: actions/setup-java@v4
            with: 
               distribution: 'oracle'   
               java-version: '21'    
         -  name: Cache the Maven packages
            uses: actions/cache@v4
            with: 
               path: ~/.m2
               key:  ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}      
               restore-keys: ${{ runner.os }}-m2  
         -  name:  Build with Maven
            run:   mvn clean install  
         -  name: Publish
            id: publish
            run: find target/*.jar -type f -execdir echo 'artifact={}' >> $GITHUB_OUTPUT ';'     
         -  name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
               path: target/*.jar
               name: package          
   deploye:
      needs: build
      runs-on: ubuntu-latest
      steps: 
       -  name: Get build artifact
          uses: actions/download-artifact@v4
          with:
            name: package
       - name: Set java env
         uses: actions/setup-java@v4
         with:
           distribution: 'oracle'
           java-version: '21'
       -  name:  Run Spring Boot
          run:  mvn spring-boot:run
       -  name: get artifact name
          run : echo ${{ needs.build.outputs.artifact-file }}  
       -  name: Deploy
          run: echo "Deploying..................."       

      
