name: Java Springboot Project with Composite Action
on: 
 push:
    branches:
        - main
jobs:     
   test: 
     runs-on: ubuntu-latest
     steps:
      -  id: checkout-out
         name: Checkout
         uses: actions/checkout@v4
      -  name: Install java and cache dependencies
         uses: ./.github/workflows/actions/composite-action-cached-deps  
      -  name: Unit Testing
         id: testing-code
         run: mvn  test
      -  name: Upload test Report
         if: failure() && steps.testing-code.outcome == 'failure'
         uses: actions/upload-artifact@v4
         with:
            path: target/surefire-reports/*.xml
            name: test-report   
   build:
        needs: test
        runs-on: ubuntu-latest
        outputs:
          artifact-file: ${{ steps.publish.outputs.artifact}}
        steps: 
         -  id: checkout-out
            name: Checkout
            uses: actions/checkout@v4
         -  name: Install java and cache dependencies
            uses: ./.github/workflows/actions/composite-action-cached-deps         
         -  name:  Build with Maven
            run:   mvn clean install  -Dmaven.test.skip=true
         -  name: Publish
            id: publish
            run: find target/*.jar -type f -execdir echo 'artifact={}' >> $GITHUB_OUTPUT ';'     
         -  name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
               path: target/*.jar
               name: package          
   deploye:
      needs: build
      runs-on: ubuntu-latest
      steps: 
       -  id: checkout-out
          name: Checkout
          uses: actions/checkout@v4        
       -  name: Get build artifact
          uses: actions/download-artifact@v4
          with:
            name: package
       -  name: Install java and cache dependencies
          uses: ./.github/workflows/actions/composite-action-cached-deps  
       -  name:  Run Spring Boot
          run:  echo "$MYSQL_ROOT_PASSWORD"
       -  name: get artifact name
          run : echo ${{ needs.build.outputs.artifact-file }}  
       -  name: Deploy
          run: echo "Deploying...."  

   report:
      if: failure()
      needs: [test,deploye,build]
      runs-on: ubuntu-latest
      steps:
       - name: Output Information
         run: |
            echo "Something went wrong"
            echo "${{ toJson(github) }}"
   reuseable:
      needs: build
      uses: ./.github/workflows/reuseable.yml      
      with:
         artifact-name: package
   reuseable-output-result:
      needs: reuseable
      runs-on:  ubuntu-latest
      steps:
         - name: Print  reuseable job output
           run: echo "${{ needs.reuseable.outputs.results }}"    

     


      
