name: Java deployemt workflow
on: push
jobs:
  build_and_test:
     runs-on: ubuntu-latest
     steps: 
       - name: Get Code
         uses: actions/checkout@v4
       - name: Set up JDK 21
         uses: actions/setup-java@v4  
         with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '21'  
          
       - name: Cache the Maven packages
         uses: actions/cache@v4
         with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2  
       - name: Build project with Maven
         run: mvn -B package --file pom.xml
  publish-job:
      runs-on: ubuntu-latest
      steps: 
        - name: Get Code
          uses: actions/checkout@v4
        - name:  Setup JDK 21
          uses:  actions/setup-java@v4    
          with: 
            distribution: 'oracle' # See 'Supported distributions' for available options
            java-version: '21'    
        - name: Cache the Maven packages
          uses: actions/cache@v4
          with:
             path: ~/.m2
             key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
             restore-keys: ${{ runner.os }}-m2  
        - name: Build project with Maven
          run: mvn -B package --file pom.xml   -DskipTests
        - name: Create  artifact
          run:  mkdir staging && cp target/*.jar staging       
        - name: Upload artifact
          uses:  actions/upload-artifact@v1
          with:
            name:  Package
            path: staging


    