name: Defining outputs for a job
on: workflow_dispatch
jobs:
    define-output:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.step1.outputs.test }}
            output2: ${{ steps.step2.outputs.test }}
        steps:
          - id: step1
            name: step 1
            run: echo "test=hello" >> "$GITHUB_OUTPUT"
          - id: step2
            name: step 2
            run:  echo "test=world" >> "$GITHUB_OUTPUT" 
    print-output:
        runs-on: ubuntu-latest
        needs: define-output
        steps:
         - env:
            OUTPUT1: ${{ needs.define-output.outputs.output1}}
            OUTPUT2: ${{ needs.define-output.outputs.output2}}
           run: |
             echo $OUTPUT1
             echo $OUTPUT2
    context-data:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "${{ toJson(github) }}"         


              


             


