name: Defining outputs for a job
on: workflow_dispatch
jobs:
    define-output:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{ steps.output1.outputs.test1 }}
            output2: ${{ steps.output2.outputs.test2 }}
        steps:
         -  id: output1
            name: test1 output
            run : echo "test1=Hello" >> "$GITHUB_OUTPUT"
         -  id: output2
            name: test2 output
            run: echo "echo test2=World"   
    print-outputs:
        runs-on: ubuntu-latest
        needs:   define-output
        steps:
          - env: 
             OUTPUT1: ${{ needs.define-output.outputs.output1 }}
             OUTPUT2: ${{ needs.define-output.outputs.output2 }}
            run: echo "$OUTPUT1 $OUTPUT2"

              


             


