name: Reuseable Workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name Artifact
                required: false
                default: package
                type: string  
        outputs:
            results:
                description: The name Artifact
                value:  ${{ jobs.call-reuseale-workflow.outputs.outcome }}       
jobs:
   call-reuseale-workflow:
      outputs:
        outcome: ${{ steps.result-id.outputs.step-result }}
      runs-on: ubuntu-latest
      steps:
        - name: Get Artifact
          uses: actions/download-artifact@v4
          with:
            name:   ${{ inputs.artifact-name }}  
        - name: List Files
          run: ls    
        - name: After deploye
          run: echo "calling Reuseable Workflow"
        - name: Set result output
          id: result-id
          run: echo "step-result=sucess" >> $GITHUB_OUTPUT
